modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

${mod_mixins}

[["dependencies.${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[["dependencies.${mod_id}"]]
modId = "yet_another_config_lib_v3"
mandatory = true
ordering = "NONE"
side = "BOTH"
